#!/usr/bin/env bash
set -e

source .env
source .secrets

export PGPASSWORD=$POSTGRES_PASSWORD

psql -v ON_ERROR_STOP=1 --host "$REVIEW_DB_HOST" --port "$REVIEW_DB_PORT" --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  DROP DATABASE IF EXISTS $REVIEW_DB_DATABASE;
  DROP ROLE IF EXISTS $REVIEW_DB_USERNAME;
	CREATE USER $REVIEW_DB_USERNAME WITH PASSWORD '$REVIEW_DB_PASSWORD';
	CREATE DATABASE $REVIEW_DB_DATABASE;
	GRANT ALL PRIVILEGES ON DATABASE $REVIEW_DB_DATABASE TO $REVIEW_DB_USERNAME;
EOSQL