variable "owner" {}
variable "deployment_target" {}
variable "ec2_type" {}
variable "ec2_usage" {}
variable "app_port" {}
variable "key_name" {}
variable "eip_tag_name" {}
variable "public_subnet_id" {}
variable "vpc_id" {}
variable "vpc_cidr_block" {}
variable "fs_id" {}
variable "fsap_dropbox_id" {}
variable "fsap_config_id" {}
//variable "database_cidr_blocks" {}
