variable "owner" {}
variable "deployment_target" {}
variable "web_ec2_type" {}
variable "key_name" {}
variable "eip_tag_name" {}
variable "public_subnet_id" {}
variable "vpc_id" {}
variable "vpc_cidr_block" {}
//variable "database_cidr_blocks" {}
