<?php

/**
 * This is a Read-only adapter to the Link model class that add a  formatted ephemeral property to the model
 *
 * That property is not meant to be saved in database.
 * The other properties available Link are accessible from this class too through delegation
 *
 * @param Link $link the link instance to enrich with addtional property
 * @param string $format  HTML snippet generated by FormattedDatasetAccessions
 *
 * @property string $prefered_source
 * @property int $id
 * @property int $dataset_id
 * @property string $link
 * @property boolean $is_primary
 *
 * @author Rija Menage <rija+git@cinecinetique.com>
 * @license GPL-3.0
 */
class LinkWithFormat extends yii\base\BaseObject implements LinkInterface
{
    /**
     * @var string $_format hold HTML snippet for displaying that link as generated by FormattedDatasetAccessions
     */
    private $_format;

    /**
     * @var Link $_link hold the Link object for which this is an adapter
     */
    private $_link;


    public function __construct(LinkInterface $link, string $format)
    {
        $this->_format = $format;
        $this->_link = $link;
    }

    public function getFormat(): string
    {
        return $this->_format;
    }

    public function getId()
    {
        return $this->_link->id;
    }

    public function getDataset_Id()
    {
        return $this->_link->dataset_id;
    }

    public function getLink()
    {
        return $this->_link->link;
    }

    public function getIs_Primary()
    {
        return $this->_link->is_primary;
    }

    public function getFullUrl(string $link_type = ''): string
    {
        return $this->_link->getFullUrl($link_type);
    }
}
