- name: Allow centos user to use docker (add centos to group)
  command: usermod -aG docker centos

- name: Enable systemd service
  command: systemctl enable docker

- name: Creates directory
  file:
    path: /etc/systemd/system/docker.service.d/
    state: directory

- name: Create an override for docker systemd service
  copy:
    src: override.conf
    dest: /etc/systemd/system/docker.service.d/override.conf
    owner: root
    group: root
    mode: 0644

- name: Reload systemd docker service
  command: systemctl daemon-reload

- name: Restart systemd docker service
  command: systemctl restart docker.service

- name: Backup the CA
  fetch:
    src: /home/centos/.docker/ca.pem
    dest: output/certs-{{ target_environment }}/
    flat: yes

- name: Backup the cert
  fetch:
    src: /home/centos/.docker/cert.pem
    dest: output/certs-{{ target_environment }}/
    flat: yes

- name: Backup the key
  fetch:
    src: /home/centos/.docker/key.pem
    dest: output/certs-{{ target_environment }}/
    flat: yes