
XLSUploaderDeployLive:
  stage: live deploy
  extends: .tag_only
  variables:
    TARGET_ENV: live
    REMOTE_WEBAPP_DOCKER: "$remote_public_ip:2376"
    REMOTE_BASTION_DOCKER: "$remote_bastion_public_ip:2376"
  script:
    # Deployment to bastion server
    - mkdir -pv ~/.docker
    - bash -c "echo '$docker_bastion_tlsauth_ca' >  ~/.docker/ca.pem"
    - bash -c "echo '$docker_bastion_tlsauth_cert' > ~/.docker/cert.pem"
    - bash -c "echo '$docker_bastion_tlsauth_key' > ~/.docker/key.pem"
    - docker --tlsverify -H=$REMOTE_BASTION_DOCKER info
    - docker --tlsverify -H=$REMOTE_BASTION_DOCKER login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker --tlsverify -H=$REMOTE_BASTION_DOCKER pull registry.gitlab.com/$CI_PROJECT_PATH/production_xls_uploader:$TARGET_ENV
    - docker --tlsverify -H=$REMOTE_BASTION_DOCKER pull registry.gitlab.com/$CI_PROJECT_PATH/production_pgclient:$TARGET_ENV
  environment:
    name: $TARGET_ENV
  artifacts:
    paths:
      - gigadb/app/tools/excel-spreadsheet-uploader/.env
      - .env
      - .secrets
      - .ci_env
    when: always
    expire_in: 3 days
  needs: ["XLSUploaderBuildLive"]
