version: '3.7'

services:
  production-files-metadata-console:
    build:
      context: ../../../..
      dockerfile: gigadb/app/tools/files-metadata-console/Dockerfile-Production
      cache_from:
        - "registry.gitlab.com/$CI_PROJECT_PATH/production-files-metadata-console:$GIGADB_ENV"
