version: '3.7'
services:

  tool:
    build:
      context: .
    volumes:
      # Mount source-code for development
      - .:/app
      - .:/logs
      # For using classes in GigaDB models and services
      - ../../../:/gigadb
      # For accessing pgdmp database dumps
      - ../../../../sql:/app/sql
      # Destination for readme files
      - ./runtime/curators:/home/curators
    networks:
      # Connect to db-tier network in ops/docker-compose.yml
      - proxy-db-tier

  configure:
    image: rija/docker-alpine-shell-tools:1.0.1
    working_dir: /gigadb/app/tools/readme-generator
    volumes:
      - ./:/gigadb/app/tools/readme-generator:delegated
      - ../../configurator:/gigadb/app/configurator:ro
    command: /gigadb/app/tools/readme-generator/configure

networks:
  proxy-db-tier:  # represents db-tier network in ops/docker-compose.yml
    name: ${GIGADB_COMPOSE_PROJECT_NAME}_db-tier
    external: true
