version: '3.7'

services:

  web:
    image: nginx:${NGINX_VERSION}-alpine
    volumes:
      - ./:/var/www
      - ${DATA_SAVE_PATH}/${COMPOSE_PROJECT_NAME}/nginx/sites-available:/etc/nginx/sites-available
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-conf/upstream.conf:/etc/nginx/conf.d/upstream.conf:ro
    ports:
      - "${PUBLIC_HTTP_PORT}:80"
      - "${PUBLIC_HTTPS_PORT}:443"
    networks:
      - web-tier

  application:
    env_file: container-env.dev
    image: gigascience/gigadb-website:php-${PHP_VERSION}-rel-#{GIGADB_RELEASE}
    volumes:
      - ./:/var/www
      - ${DATA_SAVE_PATH}/${COMPOSE_PROJECT_NAME}/yii:${YII_PATH}
      - ./php-conf/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./php-conf/gigadb.ini:/usr/local/etc/php/conf.d/gigadb.ini
    expose:
      - "9000"
    networks:
      - web-tier
      - db-tier

  database:
    image: postgres:${POSTGRES_VERSION}-alpine
    env_file: container-env.dev
    volumes:
      - ${DATA_SAVE_PATH}/${COMPOSE_PROJECT_NAME}/postgres:/var/lib/postgresql
      - ./sql/gigadb_testdata.sql:/docker-entrypoint-initdb.d/1-gigadb_testdata.sql
    networks:
      - db-tier

  init:
    image: php:${PHP_VERSION}-cli
    volumes:
      - ./:/var/www
      - ${DATA_SAVE_PATH}/${COMPOSE_PROJECT_NAME}/yii:${YII_PATH}
    depends_on:
      - application
      - web
      - database
    command: /var/www/protected/yiic lesscompiler
    networks:
      - web-tier


networks:
  web-tier:
  db-tier:
