version: '3.7'

services:

  application:
    build:
      cache_from:
        - "${CI_PROJECT_NAME}_application:latest"

  test:
    build:
      cache_from:
        - "${CI_PROJECT_NAME}_test:latest"
