site_name: GigaDB Documentation
repo_url: https://github.com/gigascience/gigadb-website/
nav:
  - Home: index.md

theme:
  name: material
  language: en
  highlights: true
  color_mode: auto
  features:
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.highlight
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.select
    - content.code.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

