variable "owner" {}
variable "deployment_target" {}
variable "gigadb_db_database" {}
variable "gigadb_db_user" {}
variable "gigadb_db_password" {}
variable "vpc_id" {}
variable "rds_subnet_ids" {}
variable "snapshot_identifier" {}
variable "restore_to_point_in_time" {}