- name: Install pre-requisites to Docker-CE
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: enable Docker-CE stable repo
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: enable Docker-CE edge repo
  shell: yum-config-manager --enable docker-ce-edge

- name: Install Docker-CE package
  yum:
    name: docker-ce
    state: present
    enablerepo: docker-ce-edge

- name: Install Docker Compose package 1.24
  shell: "curl -L \"https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)\" -o /usr/local/bin/docker-compose"
  sudo: true

- name: Make docker compose executable
  command: chmod +x /usr/local/bin/docker-compose
  sudo: true
  # yum:
  #   name: docker-compose
  #   state: present
  #   enablerepo: docker-ce-edge
