#!/bin/bash

set -e
set -u

profile=${1:-"local"}

# before running tests, run migration for test database first (FUW)
# docker-compose exec -T console /app/yii_test migrate --interactive=0
# before running tests, run migration for main database first (GigaDB)
docker-compose run --rm application ./protected/yiic migrate --interactive=0
# before running tests, run migration for main database first (FUW)
docker-compose exec -T console /app/yii migrate --interactive=0
docker-compose run --rm test bin/behat --profile $profile -v --stop-on-failure
docker-compose exec -T console /app/vendor/bin/codecept -c /app/common run -g ok acceptance --fail-fast