#!/usr/bin/env bash

set -e -u

echo "About to run  automated tests..."

echo "Loading environment..."
set -a
source /var/www/.env
source /var/www/.secrets
set +a

echo "First, backup the main database..."
exec 3>&1
exec 1> /dev/null
pg_dump $GIGADB_DB -U $GIGADB_USER -h $GIGADB_HOST -F custom  -f /var/www/sql/before-run.pgdmp
exec 1>&3

echo "Running acceptance tests"
if [[ "$GIGADB_ENV" == "dev" ]];then
	bin/behat --tags "@ok" -v --stop-on-failure
else
	# we are on CI with remote runner, affilate login tests don't work becasause Google and Twitter block it
	bin/behat --tags "@ok&&~@affiliate-login&&~@javascript" -v --stop-on-failure
fi

echo "...all automated tests have run"

echo "Lastly, restoring the main database..."
exec 3>&1
exec 1> /dev/null
pg_restore -i -h $GIGADB_HOST  -U $GIGADB_USER -d $GIGADB_DB -c -v /var/www/sql/before-run.pgdmp
exec 1>&3