#!/usr/bin/env bash

set -e -u -x
set -a
source /var/www/.env
source /var/www/.secrets
set +a

echo "Running acceptance tests..."
if [[ "$GIGADB_ENV" == "dev" ]];then
	bin/behat --tags "@ok&&~@facebook&&~@affiliate-login" -v --stop-on-failure
else
	# we are on CI with remote runner, affilate login tests don't work becasause Google and Twitter block it
	bin/behat --tags "@ok&&~@affiliate-login&&~@javascript" -v --stop-on-failure
fi
