#!/usr/bin/env bash

set -e -u -x
set -a
source /var/www/.env
source /var/www/.secrets
set +a

echo "Running acceptance tests..."
if [[ "$GIGADB_ENV" == "dev" ]];then
	bin/behat --profile local -v --stop-on-failure
else
	bin/behat --profile ci -v --stop-on-failure
fi
