#!/usr/bin/env bash

set -e -u

set -a
source .env
set +a

./tests/unit_runner
./tests/functional_runner
./tests/acceptance_runner cli
./tests/css_check
./tests/javascript_check
./tests/coverage_runner

