#!/bin/bash

set -e -u

set -a
source .env
set +a

./tests/unit_runner
./tests/functional_runner
docker-compose run --rm test ./tests/css_check
docker-compose run --rm test ./tests/javascript_check
./tests/acceptance_runner ci-js
./tests/coverage_runner

