#!/usr/bin/env bash

set -x -u -e

echo "Preparing to run behave test..."

echo "Loading environment..."
set -a
source /var/www/.env
source /var/www/.secrets
set +a

if [ "$GIGADB_ENV" != "dev" ];then
	echo "Behave tests should be run only in dev envirorment..."
    exit
fi

echo "Backing up database..."
exec 3>&1
exec 1> /dev/null
pg_dump $GIGADB_DB -U $GIGADB_USER -h $GIGADB_HOST -F custom -f /var/www/sql/before-run.pgdmp
exec 1>&3

echo "Preparing the database for bahave tests..."
exec 3>&1
exec 1> /dev/null
pg_restore -h $GIGADB_HOST -U $GIGADB_USER -d $GIGADB_TEST_DB --clean --no-owner -v /var/www/sql/gigadb_testdata.pgdmp || true
exec 1>&3

echo "Running behave tests..."
behave /var/www/protected/tests/behave
echo "...behave tests finished"

echo "Restoring original database..."
exec 3>&1
exec 1> /dev/null
pg_restore -h $GIGADB_HOST  -U $GIGADB_USER -d $GIGADB_DB --clean --no-owner -v /var/www/sql/before-run.pgdmp
exec 1>&3

echo "Done!"
