#!/usr/bin/env bash

set -x -u -e

echo "Preparing to run behave test..."

echo "Loading environment..."
set -a
source /var/www/.env
source /var/www/.secrets
set +a

if [ "$GIGADB_ENV" != "dev" ];then
	echo "Behave tests should be run only in dev envirorment..."
    exit
fi

#echo "Preparing the database for bahave tests..."
#exec 3>&1
#exec 1> /dev/null
#psql -U $GIGADB_USER -h $GIGADB_HOST < /var/www/sql/staging_prepare.sql
#psql -U $GIGADB_USER -h $GIGADB_HOST $GIGADB_TEST_DB < /var/www/sql/staging.sql
#exec 1>&3

echo "Running behave tests..."
behave /var/www/protected/tests/behave/features
echo "...behave tests finished"

echo "Done!"
