#!/usr/bin/env bash

set -e -u

set -a
echo "Loading environment..."
source "./.env"
echo "Loading credentials data"
source "/var/www/.secrets"
set +a

printf "\nRunning PHPUnit coverage\n"

echo "Preparing the test database..."
exec 3>&1
exec 1> /dev/null
psql -U $GIGADB_USER -h $GIGADB_HOST < /var/www/sql/gigadb_unit_tests.sql
exec 1>&3

./bin/phpunit protected/tests  --verbose --configuration protected/tests/phpunit.xml

./bin/php-coveralls --verbose --coverage_clover /var/www/protected/runtime/clover.xml --json_path /var/www/protected/runtime/coveralls-upload.json

cat /var/www/protected/runtime/phpunit-coverage.txt
