#!/bin/bash

set +e
set -u


docker-compose run test php -dpcov.enabled=1 -dpcov.directory=protected ./vendor/codeception/codeception/codecept run unit --coverage

docker-compose run test ./vendor/codeception/codeception/codecept run functional --coverage

docker-compose run test ./vendor/codeception/codeception/codecept run acceptance --coverage

docker-compose run test ./vendor/codeception/codeception/codecept run api --coverage
