#!/usr/bin/env bash
set -e

echo "Checking for CSS errors..."
csslint_output=$(csslint css/current.css)

if [[ $(echo "$csslint_output" | grep -c "error" || true) -eq "0" ]]; then
  echo "No CSS errors detected by CSSLint"
  exit 0
else
  echo "CSSLint detected CSS errors - check tmp/css_errors.txt"
  # Output file with errors
  echo "$csslint_output" > "/var/www/tmp/css_errors.txt"
  exit 1
fi
