#!/usr/bin/env bash

set -e
set -u

set -a
echo "Loading environment..."
source "./.env"
echo "Loading credentials data"
source "/var/www/.secrets"
set +a

printf "\nRunning PHPUnit functional tests\n"

echo "Preparing the database for functional tests..."
exec 3>&1
exec 1> /dev/null
pg_restore -h $GIGADB_HOST -U $GIGADB_USER -d $GIGADB_DB --clean --no-owner -v /var/www/sql/gigadb_testdata.pgdmp || true
exec 1>&3

./bin/phpunit protected/tests/functional  --verbose --configuration protected/tests/phpunit.xml --no-coverage
