#!/bin/bash

set -e
set -u

# before running tests, run migration for main database first (GigaDB)
docker-compose run --rm application ./protected/yiic migrate --interactive=0
# running functional tests for GigaDB, make sure to reference the appropriate bootstrap, so database can be loaded and restored properly
docker-compose run --rm test ./bin/phpunit --testsuite functional --bootstrap protected/tests/functional_custom_bootstrap.php --verbose --configuration protected/tests/phpunit.xml --no-coverage
# before running tests, run migration for main database first (FUW)
docker-compose exec -T console /app/yii migrate --interactive=0
# running functional tests for File Upload Wizard's backend and frontend apps
docker-compose exec -T console /app/vendor/bin/codecept -c /app/backend run functional
docker-compose exec -T console /app/vendor/bin/codecept -c /app/frontend run functional