#!/usr/bin/env bash

set -e  # Stop script execution if error encountered

echo "Checking for Javascript errors..."

# Grep for errors detected by JSHint
output=$(jshint --verbose style-guide/js/sg-scripts.js | grep -E "E[0-9]+.$")

if [[ $(echo "$output" | wc -l) -ge "0" ]]; then
  echo "JSHint detected Javascript errors!"
  # Output file with errors
  echo "$output" > "tmp/js_errors.txt"
  exit 1
else
  echo "No Javascript errors detected by JSHint"
  exit 0
fi
