#!/usr/bin/env bash

set -e
set -u

echo "About to run  automated tests..."

echo "Loading environment..."
source "./.env"

if [[ "$GIGADB_ENV" == "dev" ]];then
	echo "Loading test users"
	set -a
	source /var/www/.secrets
	set +a
fi

echo "First, backup the main database..."
pg_dump $GIGADB_DB -U $GIGADB_USER -h $GIGADB_HOST -F custom  -f /var/www/sql/before-run.pgdmp > /var/www/protected/runtime/pg_dump.log 2>&1

# echo "Running acceptance tests"
bin/behat --tags @ok -v --stop-on-failure -c tests/behat.yml

echo "Preparing the test database..."
psql -U $GIGADB_USER -h $GIGADB_HOST < /var/www/sql/gigadb_unit_tests.sql > /var/www/protected/runtime/setup_test_database.log 2>&1


echo "Running unit tests"
cd /var/www/protected/tests && ./../../bin/phpunit --config=phpunit.xml --coverage-html /var/www/protected/runtime/coverage  unit

echo "...all automated tests have run"

echo "Lastly, restoring the main database..."
pg_restore -i -h $GIGADB_HOST  -U $GIGADB_USER -d $GIGADB_DB -c -v /var/www/sql/before-run.pgdmp > /var/www/protected/runtime/pg_restore.log 2>&1
