#!/usr/bin/env bash

set -e
set -u

echo "About to run  automated tests..."

echo "Loading environment..."
set -a
source "./.env"
set +a

echo "Loading test users"
set -a
source /var/www/.secrets
set +a

echo "First, backup the main database..."
pg_dump $GIGADB_DB -U $GIGADB_USER -h $GIGADB_HOST -F custom  -f /var/www/sql/before-run.pgdmp

echo "Running acceptance tests"
if [[ "$GIGADB_ENV" == "dev" ]];then
	bin/behat --tags "@ok" -v --stop-on-failure -c tests/behat.yml
else
	# we are on CI with remote runner, affilate login tests don't work becasause Google and Twitter block it
	bin/behat --tags "@ok&&~@affiliate-login" -v --stop-on-failure -c tests/behat.yml --format=html --out=/var/www/protected/runtime/features.html
fi

echo "Preparing the test database..."
psql -U $GIGADB_USER -h $GIGADB_HOST < /var/www/sql/gigadb_unit_tests.sql


echo "Running unit tests"
if [[ "$GIGADB_ENV" == "dev" ]];then
	cd /var/www/protected/tests && ./../../bin/phpunit --config=phpunit.xml --coverage-text --coverage-clover /var/www/protected/runtime/clover.xml unit | tee -a /var/www/protected/runtime/phpunit-coverage.txt
else
	cd /var/www/protected/tests && ./../../bin/phpunit --config=phpunit.xml --coverage-text --coverage-html /var/www/protected/runtime/coverage --coverage-clover /var/www/protected/runtime/clover.xml unit | tee -a /var/www/protected/runtime/phpunit-coverage.txt
fi

echo "...all automated tests have run"

echo "Lastly, restoring the main database..."
pg_restore -i -h $GIGADB_HOST  -U $GIGADB_USER -d $GIGADB_DB -c -v /var/www/sql/before-run.pgdmp
