#!/usr/bin/env bash

set -e
set -u

set -a
echo "Loading environment..."
source "./.env"
echo "Loading credentials data"
source "/var/www/.secrets"
set +a

printf "\nRunning PHPUnit functional tests\n"

echo "Preparing the database for functional tests..."
exec 3>&1
exec 1> /dev/null
pg_restore -h $GIGADB_HOST -U $GIGADB_USER -d $GIGADB_DB --clean -v /var/www/sql/gigadb_testdata.pgdmp
exec 1>&3

./bin/phpunit protected/tests/functional  --verbose --configuration protected/tests/phpunit.xml --no-coverage

printf "\nRunning PHPUnit unit tests\n"

echo "Preparing the test database..."
exec 3>&1
exec 1> /dev/null
psql -U $GIGADB_USER -h $GIGADB_HOST < /var/www/sql/gigadb_unit_tests.sql
exec 1>&3

./bin/phpunit protected/tests/unit  --verbose --configuration protected/tests/phpunit.xml

cat /var/www/protected/runtime/phpunit-coverage.txt
