#!/usr/bin/env bash

set -e
set -u

set -a
echo "Loading environment..."
source "./.env"
echo "Loading credentials data"
source "/var/www/.secrets"
set +a

echo "Preparing the test database..."
psql -U $GIGADB_USER -h $GIGADB_HOST < /var/www/sql/gigadb_unit_tests.sql


echo "Running unit tests"
cd /var/www/protected/tests && ./../../bin/phpunit --config=phpunit.xml unit

cat /var/www/protected/runtime/phpunit-coverage.txt
