#!/usr/bin/env bash

set -e
set -u

docker-compose run --rm application ./protected/yiic_test migrate --interactive=0
docker-compose run --rm test ./bin/phpunit protected/tests/unit --verbose --configuration protected/tests/phpunit.xml --no-coverage
docker-compose exec console /app/yii_test migrate --interactive=0
docker-compose exec console /app/vendor/bin/codecept -c /app/backend run unit
docker-compose exec console /app/vendor/bin/codecept -c /app/frontend run unit
docker-compose exec console /app/vendor/bin/codecept -c /app/common run unit