#!/usr/bin/env bash

set -e
set -u

set -a
echo "Loading environment..."
source "./.env"
echo "Loading credentials data"
source "/var/www/.secrets"
set +a

echo "Preparing the test database..."
exec 3>&1
exec 1> /dev/null
psql -U $GIGADB_USER -h $GIGADB_HOST < /var/www/sql/gigadb_unit_tests.sql
exec 1>&3

./bin/phpunit protected/tests/unit --verbose --configuration protected/tests/phpunit.xml --no-coverage
