<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Welcome' => 'Welcome to',
  'Datasets and tools' => '数据集和工具',
  'Home' => '家',
  'About' => '关于',
  'Contact' => '联系',
  'Terms of use' => '使用条款',

  'Help' => '帮助',
  'Login' => '注册',
  'An account with GigaDB is required if you want to upload a dataset or be automatically notified of new content of interest to you' => '帐户与GigaDB的要求，如果你想上传一个数据集或自动通知您新的感兴趣的内容，以',
  'Create account' => '创建账户',
  'My GigaDB Page' => '我的GigaDB页',
  'Administration' => '管理',
  'LogOut' => '注销',

  'Be a fan on Facebook' => '成为Facebook上的粉丝',
  'Follow us on Twitter' => '跟随我们的Twitter',
  'Follow us on Sina' => '跟随我们的Sina',
  'Follow us on Google+' => '跟随我们的Google+',
  'GigaBlog' => '',

  'All types' => '所有类型',

  'Data released on' => '公布的数据',
  'Related manuscripts:' => '相关稿件：',
  'Related datasets:' => '相关数据集：',

  'Accessions (data included in GigaDB):' => '加入的（数据包括在GigaDB）：',
  'Accessions (data not in GigaDB):' => '加入的（数据未GigaDB）：',
  'Projects:' => '项目：',

  'Samples:' => '样品：',
  'Sample ID' => '样品编号',
  'Taxonomic ID' => '分类ID',
  'Common name' => '通用名称',
  'Genbank name' => '基因库名称',
  'Scientific name' => '学名',
  'Sample attributes' => '样品属性',

  'Files' => '档',
  '(FTP site)' => '(FTP站点)',
  '(Aspera)' => '',
  'Aspera user name: gigadb , password: gigadb' => 'Aspera的用户名：gigadb，密码：gigadb',

  'File Name' => '文件名',
  'Size' => '大小',
  'Release Date' => '发布日期',
  'File Format' => '文件格式',
  'File Type' => '文件类型',
  'Sample ID' => '样品编号',

  'Please fill out the following form with your login credentials:' => '与您的登录凭据，请填写以下表格：',
  'Fields with <span class="required">*</span> are required.' => '字段是必<span class="required">*</span>需的。',
  'Lost Password' => '忘记密码',
  'Email Address' => '电子邮件地址',
  'Password' => '密码',
  'Confirm Password' => '确认密码',
  'Remember me next time' => '下次记住我',

  'If you have lost your password, enter your email and we will send a new password to the email address associated with your account.' => '如果你已经失去了你的密码，输入您的电子邮件，我们将与您的帐户关联的电子邮件地址发送一个新的密码。',
  'Email' => '电子邮件',
  'Reset' => '复位',
  'Reset Password' => '重设密码',
  'Password Reset' => '重设密码',
  'For security reasons, we cannot tell you if the email you entered is valid or not.<br/>If it is valid, we will send new password.' => '出于安全原因，我们不能告诉你，如果你输入的电子邮件是有效或无效。<br/>如果它是有效的，我们将发送新密码。',
  'Contact us' => '联系我们',
  'if you are having problems and we will get it sorted out.' => '如果你有问题，我们会尽快整理出',

  'Your Profile Page' => '您的个人资料页',
  'First Name' => '名字',
  'Last Name' => '姓',
  'Affiliation' => '联系',
  'Add me to GigaDB\'s mailing list' => '我到GigaDB的邮件列表',

  'Change Password' => '更改密码',
  'Edit' => '编辑',
  'Save' => '节省',
  'Cancel' => '取消',
  'Upload New Dataset' => '上传新数据集',

  'Your Submitted Datasets' => '您提交的资料集',
  'DOI' => '',
  'Title' => '标题',
  'Common Name' => '通用名称',
  'Dataset Type' => 'DataSet类型',
  'Status' => '状态',
  'Publication Date' => '出版日期',
  'Modification Date' => '修改日期',

  'Search' => '搜索',
  'Search again' => '再次搜索',
  'Save current search criteria' => '保存当前的搜索条件',
  'Your Saved Searches' => '您保存的搜索',
  'Criteria' => '标准',
  'Keywords' => '关键词',
  'Load' => '加载',
  'Delete' => '删除',
  'Perform this search again' => '再次执行此搜索',

  'Dataset Results:' => '数据集的结果：',
  'File Results:' => '文件结果：',
  'How to use filters' => '如何使用过滤器',
  'Apply Filters' => '应用过滤器',
  'Project' => '项目',
  'External Link Types' => '外部链接类型',
  'File Type' => '文件类型',
  'File Format' => '文件格式',
  'File Size' => '文件大小',
  'Enable All' => '使所有',
  'Enable' => '使',
  'Disable' => '关闭',

  'Dataset' => '数据集',
  'File' => '文件',
  'Hide' => '隐藏',
  'Hide Dataset' => '隐藏数据集',
  'Show Hidden Datasets' => '显示隐藏的数据集',

  'GigaScience appreciates your interest in the GigaDB project. With a GigaDB account, you can submit new datasets to the database. Also, GigaDB can automatically notify you of new content which matches your interests. Please fill out the following information and register to enjoy the benefits of GigaDB membership!' => 'GigaScience感谢您关注在GigaDB项目的。随着一个GigaDB帐户，您可以提交新的数据集到数据库中。此外，GigaDB可以自动通知您新的内容，匹配您的利益。请填写以下信息，并注册享受的GigaDB会员！',
  'Register' => '注册',
  'Registration' => '注册',

  'Welcome!' => '欢迎！',
  'Thank you for registering with GigaDB. An account activation email will be sent to your email address shortly. To complete your account\'s activation, please click on the activation link in the account activation email.' => '感谢您注册GigaDB。不久的帐户激活电子邮件将被发送到您的电子邮件地址。为了完成您的帐户的激活，请点击激活链接激活帐户电子邮件。',
  'If you don\'t receive the email within a few minutes, please check your spam filters, or' => '如果你不\'吨在几分钟之内收到电子邮件，请检查您的垃圾邮件过滤器，或',
  'resend the email' => '重新发送电子邮件',

  'Account Activation' => '帐号激活',
  'An account activation email has been emailed to your email address.' => '一个帐号激活邮件已通过电子邮件发送到您的电子邮件地址。',
  'If you don\'t receive the email within a few minutes, please check your spam filters.' => '在几分钟之内如果您没有收到电子邮件，请检查您的垃圾邮件过滤器。',
  'Click' => '点击',
  'here' => '这里',
  'to resend the email' => '重新发送电子邮件',
  'or' => '或',
  'contact us' => '联系我们',
  'and we will get it sorted.' => '我们会得到它排序。',
  '' => '',
);

