<?php
# Generated by chef. DO NOT EDIT DIRECTLY!

$yii_path = getenv('YII_PATH');
$yiic=$yii_path. '/framework/yiic.php';
$config=dirname(__FILE__).'/config/test.php';
$composer=dirname(__FILE__).'/../vendor/autoload.php';

require_once($composer);
require_once($yiic);

