concurrent = 3
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "cicd-bot-rm"
  limit = 1
  url = "https://gitlab.com"
  token = ""
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    pull_policy = "if-not-present"
    image = "alpine:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = true
    volumes = ["/var/runner/cache:/cache:rw", "/var/runner/builds:/builds:rw"]
    shm_size = 0

[[runners]]
  name = "cicd-bot-pl"
  limit = 1
  url = "https://gitlab.com"
  token = ""
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    pull_policy = "if-not-present"
    image = "alpine:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = true
    volumes = ["/var/runner/cache:/cache:rw", "/var/runner/builds:/builds:rw"]
    shm_size = 0

[[runners]]
  name = "cicd-bot-kc"
  limit = 1
  url = "https://gitlab.com"
  token = ""
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    pull_policy = "if-not-present"
    image = "alpine:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = true
    volumes = ["/var/runner/cache:/cache:rw", "/var/runner/builds:/builds:rw"]
    shm_size = 0
