<?php
$this->pageTitle='GigaDB - Terms of use';

//echo $this->renderInternal('Yii::app()->basePath'.'/../files/html/about.html');
?>

<div class="clear"></div>
<div class="row">
	<div class="about-tabs-container">
	    <a class="btn about-tabs tab-active" href="/site/term">Terms of use</a>
	    <a class="btn about-tabs" href="/site/privacy">Privacy</a>	   
	</div>
	<div class="about1">  
		<a href="/site/term#policies">GigaScience Database (GigaDB) Use Policies</a>
		<br>
		<a href="/site/term#services">GigaDB Services</a>
		<br>
		<a href="/site/term#bgidata">BGI Data</a>
                <br>
		<a href="/site/term#disclaimer">Disclaimer</a>
		<br>
		<br>
		<a name="policies"></a>
		<h2><em>GigaScience</em> Database (GigaDB) Use Policies</h2>
		<p>
		<em>GigaScience</em> and GigaDB have a commitment to Open Science by freely providing an online database, data and services relating to data contributed from biological and biomedical science experiments by <em>GigaScience</em> authors and other collaborators. <em>GigaScience</em> and BGI impose no additional restrictions on access to, or use of, the data provided. Data generated by the BGI and its collaborators is released into the public domain in accordance with community norms for scholarly communication. Data associated with <em>GigaScience</em> journal is specifically released under a Creative Commons <a href="http://creativecommons.org/about/cc0" target="_blank">CC0</a> waiver. While this waives any legal requirement for attribution, crediting the source of research findings and data are cultural norms and expected etiquette for science. These Open Science policies and practices are therefore only sustainable if scientific credit is generated for all parties involved, and the BGI is playing its part in developing a global research environment that rewards data sharing.

		</p>
                <p>
                In recognition of the extensive effort that underlies these projects, we ask that you appropriately acknowledge the use of any preliminary data. To aid researchers to find, access, and reuse data, we issue citable digital object identifiers for each dataset. Our recommended format for a data citation of each dataset is listed on each page. This is in accordance with the <a href="https://doi.org/10.25490/a97f-egyk" target="_blank">Data Citation Principles</a>.    
                </p>
                <p>
                GigaDB is not liable to you or third parties claiming through you, for any loss or damage. While we will retain our commitment to Open Science, we reserve the right to update these Terms of Use at any time. When alterations are inevitable, we will attempt to give reasonable notice of any changes by placing a notice on our website, but you may wish to check each time you use the website. The date of the most recent revision will appear on this, Terms of Use page.    
                </p>
                <p>
                Any questions or comments concerning these Terms of Use can be addressed to the administrator via emailing <a href="mailto:database@gigasciencejournal.com">database@gigasciencejournal.com</a>.    
                </p>
		<a name="services"></a>                               
		<h2>GigaDB Services</h2>
                <p>GigaDB, <em>GigaScience</em> and the BGI provide these data in good faith, but make no warranty, expressed or implied, nor assume any legal liability or responsibility for any purpose for which they are used. </p>
                <p>
                GigaDB will make all reasonable effort to maintain continuity of these online services and provide adequate warning of any changes or discontinuities. However, GigaDB accepts no responsibility for the consequences of any temporary or permanent discontinuity in service.    
                </p>
                <p>
                All feedback provided to GigaDB on its online services will be treated as non-confidential unless the individual or organisation providing it states otherwise.
Any attempt to use GigaDB online services to a level that prevents, or looks likely to prevent, GigaDB providing services to others, will result in that use being blocked. GigaDB will attempt to contact the user to discuss their needs and how (and if) these can be met from other sources.
                </p>
                <p>
                    Some of the data provided from external sources may be subject to third-party constraints. Users are solely responsible for establishing the nature of and complying with any such intellectual property restrictions. Any software from GigaDB made available for download through our web pages (either directly or from third party repositories like <a href="https://github.com/">GitHub</a>) will have its own individual license agreement.    
                </p>


		
		<a name="bgidata"></a>

		<h2>BGI Data</h2>
                <p>
                As one of the world’s largest biological data producers, the BGI’s goal is to maximize the use of its data by providing it to the research community in a timely manner. At the same time, BGI recognizes the need for researchers to be appropriately credited for their scientific contribution and investment in data generation. It is therefore expected that all researchers both honor agreements in line with the <a href="http://www.genome.gov/10506537">Fort Lauderdale</a> and the <a href="http://www.nature.com/nature/journal/v461/n7261/full/461168a.html">Toronto International Data Release Workshop</a> data sharing principles and appropriately acknowledge the contributions of others.    
                </p>
                <p>
                Accordingly, raw data such as individual sequence read traces are submitted to the relevant database as soon as they have exited our quality control pipelines. Whole genome sequence assemblies are released as soon as possible following appropriate quality analysis. Our repository contains draft versions of genome sequence assemblies, and we ask that you understand that these represent preliminary data, subject to omissions and errors. In addition, whole genome assemblies are likely to change upon the availability of new data, and our website will document new assembly versions as they are released.   
                </p>
                <p>
                    In recognition of the extensive effort that underlies these projects, we ask that you appropriately acknowledge the use of any preliminary data. To aid researchers to find, access, and reuse data, we have issued citable digital object identifiers for each dataset. Our recommended format for a data citation of each dataset is listed on each page. This recommendation is in accordance with the adopted guidelines by the genome sequencing community in a statement of principles for the distribution and use of large-scale sequencing data: <a href="http://www.wellcome.ac.uk/About-us/Publications/Reports/Biomedical-science/WTD003208.htm">Community Resource Projects</a> and the resulting <a href="http://www.genome.gov/page.cfm?pageID=10506537">NHGRI policy statement</a>. If you have any questions regarding the use of this data, please contact us at <a href="mailto:database@gigasciencejournal.com">database@gigasciencejournal.com</a>. In line with research norms, we request that you ask us before publishing analyses of the sequences on a genome scale. We welcome collaborative interaction to provide the community with improved whole genome analyses and annotations.    
                </p>
                
                <a name="disclaimer"></a>

		<h2>Disclaimer</h2>
                <p>
                Some of the data provided from external sources may be subject to third-party constraints. Users are solely responsible for establishing the nature of and complying with any such intellectual property restrictions.    
                </p>
                <p>
                <em>GigaScience</em> and the BGI provide this data in good faith, but make no warranty, expressed or implied, nor assume any legal liability or responsibility for any purpose for which they are used.    
                </p>
		

     
    </div>
</div>

