version: '2'
services:

  tool:
    build:
      context: .
    volumes:
      # Mount source-code for development
      - .:/app
      - .:/logs

  config:
    image: rija/docker-alpine-shell-tools:1.0.1
    volumes:
      - .:/app
    command: /app/generate_config.sh
