maintainer       "Cogini"
maintainer_email "phu@cogini.com"
license          "All rights reserved"
description      "Installs/Configures main"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.0.1"
name			 "gigadb"

depends "apt"
depends "yii"
depends "php"
depends "nginx"
depends "postgresql"
depends "python"
depends "poise-python"
depends "nodejs"
depends "sphinx"
depends "elasticsearch"
