- name: Copying Let's encrypt config in place
  command: /usr/local/bin/docker-compose exec -T web cp /etc/nginx/conf.d/le.ini /etc/letsencrypt/cli.ini
  args:
    chdir: /home/centos/infrastructure
  register: le_status


- name: list the content of /etc/letsencrypt
  command: /usr/local/bin/docker-compose exec -T web ls -alrt /etc/letsencrypt
  args:
    chdir: /home/centos/infrastructure
  register: le_status

- debug:
    msg: "{{ le_status.stdout }}"

- name: Create certificate
  command: "/usr/local/bin/docker-compose run --rm certbot certonly -d {{ app_url }}"
  args:
    chdir: /home/centos/infrastructure
  register: https_create_status

- debug:
    msg: "{{ https_create_status.stdout }}"

- name: Enable https in nginx
  command: /usr/local/bin/docker-compose exec -T web mv /etc/nginx/conf.d/https.conf.disabled /etc/nginx/conf.d/https.conf
  args:
    chdir: /home/centos/infrastructure
  register: https_status

- debug:
    msg: "{{ https_status.stdout }}"

- name: Restart nginx
  command: /usr/local/bin/docker-compose kill -s HUP web
  args:
    chdir: /home/centos/infrastructure
  register: nginx_status

- debug:
    msg: "{{ nginx_status.stdout }}"
