variable "owner" {}
variable "deployment_target" {}
variable "bastion_ec2_type" {}
variable "key_name" {}
variable "eip_tag_name" {}
variable "public_subnet_id" {}
variable "vpc_id" {}
variable "fs_id" {}
variable "fasp_dropbox" {}
variable "fasp_config" {}
