---
# build a Centos server running a secure Docker CE install

- name: Setup Fail2ban
  hosts: staging_dockerhost

  tasks:
    - debug:
        msg: "target host: {{ inventory_hostname }}"

  roles:
    - role: fail2ban
    - role: jail-ssh

- name: Setup Docker CE
  hosts: staging_dockerhost

  tasks:
    - debug:
        msg: "target host: {{ inventory_hostname }}"

  roles:
    - role: docker-install
    - role: role-secure-docker-daemon
      dds_host: 0.0.0.0
      dds_server_cert_path: /etc/docker
      dds_restart_docker: no
    - role: docker-postinstall
    - role: postgres-install
    - role: ansible-role-postgresql
      postgresql_version: 9.4
      postgresql_databases:
      - name: gigadb
      postgresql_global_config_options:
      - option: listen_addresses
        value: '*'
      postgresql_hba_entries:
      - { type: local, database: all, user: postgres, auth_method: peer }
      - { type: local, database: all, user: all, auth_method: peer }
      - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5 }
      - { type: host, database: all, user: all, address: '::1/128', auth_method: md5 }
      - { type: host, database: all, user: all, address: 'samenet', auth_method: md5 }
