#!/usr/bin/env bash

wget http://gigadb.org/images/project/PGSClogo.jpg > /images/project/
wget http://gigadb.org/images/project/G10Klogo.jpg > /images/project/
wget http://gigadb.org/images/project/HEROIC.jpg > /images/project/
wget http://gigadb.org/images/project/ISGClogo.jpg > /images/project/
wget http://gigadb.org/images/project/IB-CASlogo.jpg > /images/project/
wget http://gigadb.org/images/project/TEMASEKlogo.jpg > /images/project/
wget http://gigadb.org/images/project/1000Genomeslogo.jpg > /images/project/
wget http://gigadb.org/images/project/carmen-image.jpg > /images/project/
wget http://gigadb.org/images/project/Pearprojectlogo.jpg > /images/project/
wget http://gigadb.org/images/project/IRRIlogo.jpg > /images/project/
wget http://gigadb.org/images/project/cgrislogo.jpg > /images/project/
wget http://gigadb.org/images/project/humangut.jpg > /images/project/
wget http://gigadb.org/images/project/catgenome.jpg > /images/project/
wget http://gigadb.org/images/project/croc.jpg > /images/project/
wget http://gigadb.org/images/project/phylogenomiclogo.png > /images/project/
wget http://gigadb.org/images/project/pinerefseq.jpg > /images/project/
wget http://gigadb.org/images/project/CardiacAtlas.jpg > /images/project/
wget http://gigadb.org/images/project/1kite.png > /images/project/
wget http://gigadb.org/images/project/EMP.png > /images/project/
wget http://gigadb.org/images/project/i5k.jpg > /images/project/
wget http://gigadb.org/images/project/cancer_cell_line.png > /images/project/
wget http://hpc-bioinformatics.cineca.it/fusion/imgs/ligea_logo1.png > /images/project/
wget http://gigadb.org/images/project/16.png > /images/project/
wget http://gigadb.org/images/project/17.png > /images/project/
wget http://gigadb.org/images/project/10kp.png > /images/project/
wget http://gigadb.org/images/project/GABRlogo.png > /images/project/
wget http://gigadb.org/images/project/KORA.jpg > /images/project/
wget http://gigadb.org/images/project/earth.jpg > /images/project/
wget http://gigadb.org/images/project/3000rice.jpg > /images/project/
wget http://gigadb.org/images/project/AOCC.png > /images/project/
wget http://gigadb.org/images/project/1KP-project.png > /images/project/
wget http://gigadb.org/images/data/cropped/100661.png > /images/project/
wget https://bioinfotraining.bio.cam.ac.uk/images/galaxy_logo.png > /images/project/
wget http://gigadb.org/images/project/citrus_greening_logo.png > /images/project/
