{
  "version": "3.1",
  "volumes": {
    "postgres_data": {}
  },
  "services": {
    "database": {
      "image": "postgres:9.4",
      "volumes": [
        "postgres_data:/var/lib/postgresql/data",
        "./database/init.sql:/docker-entrypoint-initdb.d/1-init.sql"
      ],
      "ports": [
        "8432:5432"
      ],
      "restart": "always",
      "environment": {
        "POSTGRES_PASSWORD": "postgres",
        "POSTGRES_USER": "postgres"
      }
    },
    "webserver": {
      "image": "nginx:latest",
      "volumes": [
          "./webserver/site.conf:/etc/nginx/conf.d/site.conf",
          "./code:/code"
      ],
      "ports": [
        "8080:80"
      ],
      "links": [
        "php"
      ]
    },
    "php": {
      "image": "php:7-fpm",
      "volumes": [
         "./code:/code"
      ]
    }
  }
}

