{
  "version": "3.1",
  "volumes": {
    "postgres_data": {}
  },
  "services": {
    "database": {
      "image": "postgres:9.4-alpine",
      "volumes": [
        "postgres_data:/var/lib/postgresql/data"
      ],
      "ports": [
        "8432:5432"
      ],
      "restart": "always",
      "environment": [
        "POSTGRES_PASSWORD": "gigadb",
        "POSTGRES_USER": "gigadb"
      ]
    },
    "webserver": {
      "image": "nginx:latest",
      "volumes": [
          "./webserver/site.conf:/etc/nginx/conf.d/site.conf",
          "./code:/code"
      ],
      "ports": [
        "8080:80"
      ],
      "links": [
        "app"
      ]
    },
    "app": {
      "image": "php:7-fpm",
      "volumes": [
         "./code:/code"
      ]
    }
  }
}

