version: "3.1"
services:

#    database:
#      image: postgres:9.4-alpine
#      container_name: gigadb-postgres
#      working_dir: /application
#      volumes:
#        - .:/application
#      ports:
#         - "8432:5432"
#      environment:
#        - POSTGRES_USER=postgres
#        - POSTGRES_PASSWORD=gigadb
#        - POSTGRES_DB=gigadb

    webserver:
      image: nginx:latest
#      container_name: gigadb-webserver
#      working_dir: /application
      volumes:
#          - .:/application
#          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./site.conf:/etc/nginx/conf.d/site.conf
          - ./code:/code
      ports:
        - "8080:80"

#    app:
#      build: phpdocker/php-fpm
#      container_name: gigadb-php-fpm
#      working_dir: /application
#      volumes:
#        - .:/application
#        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini

