version: '3.7'

services:

  tusd:
    ports:
      - target: 1080
        published: 9080
        protocol: tcp
        mode: host

  watcher:
    build:
      context: ../docker-inotify-command
    volumes:
      - ../inotify-config:/config:ro
      - ../incoming/ftp:/home/uploader
      - ../repo:/home/downloader/
      - ../hooks:/commands:ro
      - ../credentials:/var/access:ro
      - ../flags:/var/tmp/processing_flag
      - ../php-conf/appconfig.ini:/var/appconfig.ini:ro

  web:
    image: nginx:1.15-alpine
    volumes:
      - ../app/certs:/etc/letsencrypt
    ports:
      - target: 443
        published: 7443
        protocol: tcp
        mode: host

  cert:
    build:
      context: ../minica
    volumes:
      - ../app/certs/live:/ca
    command: --domains '*.pommetab.com'