#!/usr/bin/env bash

set -e
set -u

bin/phpdoc --visibility "public,protected" --cache-folder "docs/cache" --directory "protected/models,protected/views,protected/tests/unit,protected/controllers,features/bootstrap/" --target "docs/apidocs/"
