#!/usr/bin/env bash

set -e
set -u

php docs/phpdoc.phar --visibility "public,protected" --cache-folder "docs/cache" --directory "protected/models,protected/views,protected/tests/unit,protected/controllers,tests/features/bootstrap/" --target "docs/apidocs/"
