version: '3.7'

services:

  ftpd:
    environment:
      PUBLICHOST: ${PUBLICHOST}
      ADDED_FLAGS: "-O w3c:/var/log/pure-ftpd/transfer.log"
    command: -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P ${PUBLICHOST}

  watcher:
    build:
      context: ../docker-inotify-command
    volumes:
      - ../inotify-config:/config:ro
      - ../incoming/ftp:/home/uploader
      - ../repo:/home/downloader/
      - ../hooks:/commands:ro
      - ../credentials:/var/access:ro
      - ../tmp:/var/tmp/processing_flag
      - ../php-conf/appconfig.ini:/var/appconfig.ini:ro

  web:
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/conf.d:/etc/nginx/conf.d
      - ../html:/var/www
      - le_config:/etc/letsencrypt
      - le_webrootpath:/var/www/.le

  certbot:
    image: certbot/certbot
    volumes:
      - le_config:/etc/letsencrypt
      - le_webrootpath:/var/www/.le

volumes:
  le_config:
  le_webrootpath: