 wget http://gigadb.org/images/project/PGSClogo.jpg
 wget http://gigadb.org/images/project/G10Klogo.jpg
 wget http://gigadb.org/images/project/HEROIC.jpg
 wget http://gigadb.org/images/project/ISGClogo.jpg
 wget http://gigadb.org/images/project/IB-CASlogo.jpg
 wget http://gigadb.org/images/project/TEMASEKlogo.jpg
 wget http://gigadb.org/images/project/1000Genomeslogo.jpg
 wget http://gigadb.org/images/project/carmen-image.jpg
 wget http://gigadb.org/images/project/Pearprojectlogo.jpg
 wget http://gigadb.org/images/project/IRRIlogo.jpg
 wget http://gigadb.org/images/project/cgrislogo.jpg
 wget http://gigadb.org/images/project/humangut.jpg
 wget http://gigadb.org/images/project/catgenome.jpg
 wget http://gigadb.org/images/project/croc.jpg
 wget http://gigadb.org/images/project/phylogenomiclogo.png
 wget http://gigadb.org/images/project/pinerefseq.jpg
 wget http://gigadb.org/images/project/CardiacAtlas.jpg
 wget http://gigadb.org/images/project/1kite.png
 wget http://gigadb.org/images/project/EMP.png
 wget http://gigadb.org/images/project/i5k.jpg
 wget http://gigadb.org/images/project/cancer_cell_line.png
 wget http://hpc-bioinformatics.cineca.it/fusion/imgs/ligea_logo1.png
 wget http://gigadb.org/images/project/16.png
 wget http://gigadb.org/images/project/17.png
 wget http://gigadb.org/images/project/10kp.png
 wget http://gigadb.org/images/project/GABRlogo.png
 wget http://gigadb.org/images/project/KORA.jpg
 wget http://gigadb.org/images/project/earth.jpg
 wget http://gigadb.org/images/project/3000rice.jpg
 wget http://gigadb.org/images/project/AOCC.png
 wget http://gigadb.org/images/project/1KP-project.png
 wget http://gigadb.org/images/data/cropped/100661.png
 wget https://bioinfotraining.bio.cam.ac.uk/images/galaxy_logo.png
 wget http://gigadb.org/images/project/citrus_greening_logo.png
